package ru.iandreyshev.parserrss.models.useCase

enum class UseCaseType {
    LOAD_IMAGE_TO_ACTIVITY,
    LOAD_IMAGE_TO_FEED_ITEM,
    LOAD_AND_INSERT_ALL_RSS,
    LOAD_ARTICLE_DATA,
    LOAD_ARTICLES_FIRST_TIME,
    DOWNLOAD_AND_INSERT_RSS,
    UPDATE_RSS,
    DELETE_RSS,
    OPEN_ARTICLE_ORIGINAL
}
